---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myjavaapp-deploy
  labels:
    app: myjavaapp
spec:
  replicas: 3
  selector:
      matchLabels:
         app: myjavaapp
  template:
     metadata:
       labels:
         app: myjavaapp
     spec:
       containers:
       - name: myjavaapp-container
         image:  maha4iac/myjavaapp001122:latest
         ports:
         - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
   name: myjavaapp-svc
   labels:
     app: myjavaapp

     
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
     app: myjavaapp
 